apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: jenkins1-claim
spec:
   accessModes:
     - ReadWriteOnce
   resources:
      requests:
         storage: 700Gi
   storageClassName: gp3
   volumeName: ebs-pv