apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slave-pvc
  namespace: jenkins  # Adjust this to your desired namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  storageClassName: ebs-gp3-ap-southeast-1  # Reference the StorageClass you created
