apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3-ap-southeast-1
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.ebs.csi.aws.com/zone
        values:
          - ap-southeast-1a
          - ap-southeast-1b
          - ap-southeast-1c

~                                