apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: env1
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "delete"]

~                                                 